### ISSUE TITLE
Add missed comment annotation

### ISSUE THREAD

**Issue by peter279k** [imliam/php-name-of-person#1]
## Description

- It's the enhancement work
- I think we can some comment annotations for these methods in `Name` class

### Your environment

- latest master branch
- Linux/Ubuntu 18.04
- PHP 7.1

## Context

I think it can let developers know about every method usages via every comment annotations.

## Possible implementation

The possible implementation approaches are as follows:

- Following the `PHPDocument` style to write the comment annotations.
- The approach about writing comment annotation can refer the `NhsNumber` class in this  [repository](https://github.com/imliam/php-nhs-number/blob/master/src/NhsNumber.php).

**Comment by imliam** [comment]
Feel free to raise a merge request if you feel some of the method names are not clear - but as it stands I think each method name represents itself well enough that a comment would not be beneficial.
